### ISSUE TITLE
Please pull in fix for upstream bug for O_CLOEXEC on old linux kernels

### ISSUE THREAD

**Issue by kmsquire** [JuliaAttic/libuv-archive#1]
Hi there,

I understand that you might not want to track upstream too closely, and I guess I'm the only one who's running into this right now, and I can take care of it by hand, but when you get the chance, can you please pull in at least this upstream fix:

https://github.com/joyent/libuv/commit/1ebe14e4942c7fb69fa5a96b0bfb58a797881828

Thanks,

   Kevin

**Comment by Keno** [comment]
Done. Sry about that. Watned to do it earlier, put totally forgot about it. Thanks for reminding me.

**Comment by kmsquire** [comment]
No worries, and thanks!

Kevin

On Wed, May 9, 2012 at 6:56 PM, Keno Fischer <
reply@reply.github.com
