### ISSUE TITLE
Mysterious test failures on LP buildd instance

### ISSUE THREAD

**Issue by staticfloat** [JuliaAttic/libuv-archive#13]
I've run into some [mysterious test failures](https://launchpadlibrarian.net/137600215/buildlog_ubuntu-precise-amd64.libuv_0.9%2Bgitc793029362-juliadeps1~precise_FAILEDTOBUILD.txt.gz) on Launchpad.  I cannot reproduce locally yet, I'm going to try creating a new stripped-down ubuntu VM to see if there's some configuration locally that is different.

I'm posting this here for documentation of my progress, and to see if @vtjnash has any brilliant insights as to the source of these errors.  The fact that the tests pass just fine on my 64-bit and 32-bit VMs make me think that there's something fundamentally wrong with my setup.

**Comment by vtjnash** [comment]
I have no idea. I don't think we changed anything that would affect these tests. The threadpool and cond variable stuff was pretty recent and untested when I last rebased against upstream, which seems to have the bulk of the test failures. It also appears that there is not a readable tty device on `/dev/tty`?

**Comment by staticfloat** [comment]
I tested `joyent/libuv/master`, and they have the exact same problems.  I disabled the tests, built the package, downloaded the binaries, and tested them both with Julia and with the libuv tests recompiled against that downloaded binary.  Everything works, so I am chalking this up to the fact that buildd workers have neither a tty or network interface and calling it good.
