### ISSUE TITLE
Upstream bug: uv_hrtime() return non-incremental value under windows

### ISSUE THREAD

**Issue by mschauer** [JuliaAttic/libuv-archive#18]
I was puzzling why the `elapsed` macro is not working correctly under windows.

It turns out that this is an upstream bug in libuv, I leave a note here if somebody runs into the same problem: `uv_hrtime` can return non-incremental values under windows resulting  in underflow of `(time_ns()-t0)/1e9` in the `elapsed` macro.

Compare https://github.com/joyent/libuv/issues/850.

**Comment by StefanKarpinski** [comment]
Excellent sleuthing tracking down the cause to that libuv bug.

**Comment by vtjnash** [comment]
Since that has a patch, we can just apply that to our local branch and get the fix without waiting for upstream

**Comment by timholy** [comment]
Long ago I had to fix what was basically this same libuv bug on multiple Unix systems; I guess I didn't fix the Windows version at that time because timers are different on Windows, I lacked a Windows system to test on, and this was back before we had a Windows port. But with hindsight...

**Comment by mschauer** [comment]
Fixed upstream, joyent#850

**Comment by vtjnash** [comment]
pulled in the upstream fix in 5bf16a9b86b2b059b20703d52c1dbba5979b6f5c
