### ISSUE TITLE
Inconsistency in ./configure --help for --disable-dtrace option

### ISSUE THREAD

**Issue by psanan** [JuliaAttic/libuv-archive#30]
At commit abcbb0c (as automatically downloaded by julia at d15f183), ./configure --help produces an ambiguous line

  --disable-dtrace        enable DTrace USDT probes. [default=yes]

**Comment by tkelman** [comment]
That's just a bug in the help text of https://github.com/JuliaLang/libuv/blob/julia-uv0.11.26/m4/dtrace.m4, which no longer exists upstream.

**Comment by psanan** [comment]
Thanks - presuming that the fix will get pulled down eventually, I will close this.
