### ISSUE TITLE
Merge ability to create sockets early from upstream

### ISSUE THREAD

**Issue by amitmurthy** [JuliaAttic/libuv-archive#32]
Would be useful to have this https://github.com/libuv/libuv/pull/400 merged. Allows for certain `setsockopt` calls that need to be performed before a `bind`.

**Comment by vtjnash** [comment]
we have over 50 local commits against libuv already. i think we just need to move to a newer version of libuv already (https://github.com/JuliaLang/libuv/tree/julia-uv1.6.1alpha)

**Comment by amitmurthy** [comment]
Have we moved to a newer version of libuv?

**Comment by vtjnash** [comment]
JuliaLang/julia#12266 is green, just waiting for someone to hit merge
