### ISSUE TITLE
Failed to build on FreeBSD

### ISSUE THREAD

**Issue by ryobg** [JuliaAttic/libuv-archive#35]
Hello,

I will start with that I succeeded to build it on one FreeBSD 10.2, the second one, while I expected to be the same, had issues when building the `uv-common.c` file (note that I build in fact today's clone of Julia).

The compilation errors were related to undefined `cpu_set_t` and `CPU_SET` (and alike macros). Hence, after few hours banging my head, I hacked my way out - I just inserted near the top of the file the following lines:

``` c
#include <sys/param.h>
#include <sys/cpuset.h>
typedef cpuset_t cpu_set_t;
```

This is more for your information and reference for persons which could stuck like me.

**Comment by tkelman** [comment]
fixed by https://github.com/JuliaLang/libuv/pull/43 I believe, leave a comment and we'll reopen if not
