### ISSUE TITLE
missing uv_os_homedir

### ISSUE THREAD

**Issue by stevengj** [JuliaAttic/libuv-archive#41]
The latest version of libuv has a `uv_os_homedir` function, but this seems to be missing from the JuliaLang version?

That function would be nice to have for JuliaLang/julia#14357 and JuliaLang/julia#11331

cc @vtjnash

**Comment by tkelman** [comment]
https://github.com/JuliaLang/libuv/blob/julia-uv1.9.0/src/win/util.c#L1154

**Comment by stevengj** [comment]
Oh, that's weird.  I did a repository search for `uv_os_homedir` and it didn't show up.

**Comment by tkelman** [comment]
github doesn't allow code searching on forks, annoyingly

**Comment by vtjnash** [comment]
It would be nice if someone with admin access could break the fork link.

**Comment by tkelman** [comment]
That isn't possible for users to do, you have to contact Github support.
